engines:
  tslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
      enabled: true
ratings:
  paths:
  - src/**
exclude_paths:
- doc/**/*
- dist/**/*
- test/**/*
- vendor/**/*
