language: node_js

cache:
  directories:
  - node_modules

node_js:
  - 'stable'

sudo: false

before_install:
  - if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi
  - npm install -g typings
  - npm install -g codeclimate-test-reporter

script:
  - npm run build
  - npm run validate

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
  - node_modules/.bin/coveralls < coverage/lcov.info

before_deploy:
  - npm run build:dist && node ./script/package-dist.js

deploy:
  - provider: npm
    email: 'devmonk@mediamonks.com'
    api_key:
      secure: 'ylyExjLfQmur8ORsQo17oQvgnlBzue8W1rZhqndBHMU6IEprh3HoF1pIhBvylw6k6aMgWRn+GjGz50RcZ756kkuZxZlofthLNRF6gMKvN7aX+2SH/AUuC9UPqx4gH2MjIJwKL4SSC5HcYoujiVvAlosGd5mQ4v6gMW2vCgavdF4vIbTVokTogKgWHFUSP7zwuM30sFNtUyyB9i8vgJPepzRFSvMKRGUIIpEnN2pkA6E5sx1DgNg+0QLOf5/KCUOfFeHQ+Ly2ojCUWLhPVwfq49LxPEPObIhxFi6OmaZ4iPRjbDSTxMsE+TSAvObgDfkejaotfAsI+nUemgrwQ/tSc702i2xptSFBhWD6xAxvrVaPUVPC6Ddb2vM5Tfb1+q/AsmNiaiGcZh6TcERHi2ytNaYPo0sDDDVq9Xb7DT0TcDFA3Xaah/evEA5uYtDsoM+8ExyW71MUzEhvJHIL4qqXrr5S6rbumMaheiLv+bNj4BM8M9odKaVvKZw2K0YUB5aaEWLEEvzeQQzX5Fp6uvPOHDbKuHCRAs66vz/pzUwK2s5NZ1SruyBo1jXzmlbWr92+yH0iPq6zBmhA+SfElcfMwCmN9i4ZgmsAgQREavnCIli/+XJ2Ur8mb3jcnsPVh4yiND+3iCwa+KhTxRAIoSvb5KU3abV0TWAFAt/lhoc8Hp4'
    on:
      tags: true
      node: 'stable'
    skip_cleanup: true

  - provider: releases
    api_key:
      secure: 'ahH+HZuXibkorBAflGeMNpxYEt2JHJ+z7t+ydktQZ8Umqn+dOEubTNZNqp4kmLC8lKD/EAPggSQGuRob9zP/m9tZGMnrqfy+RpokYP0OkVJnxW9NeMNBFMshTrxgH8CecHsJU59zrSUqRJA4EJkisQCQPj+i3go/xIVIOe0gYPxzNdobj5cuMQCahaMTHAkBACNcdkMkoo0Sg6+0pf4O/mG2g2sWYk3E4je8IVQkXTVsc/72TcRWBWRFsUlO8yLWp6DvgEZjC9fl28EvJTitIYCdIibhvrGnm4kl6jjIYrZ7cqXaPDnBL7vm+TQCfitg58OFgm+SsVU36lEIjT0IMMZm9lwPIA71K+OirnYw51lL6AibYuN2krfCWYNA8HT8O6D9g5DLFDfyqK1iQmZv0KXKjL2bdhluG+KT6jKGq1A9WgybcA2+0y6/lR5pXaMCRwM5fH4Fwf5IJtUz5H/3fFt1fHkYZ+y565E5ObS8TsutqrMzuwDZehQcr9OABRgkdEyETziW6FFD1Sq22PMZzLPR/tXDz5Uf4gu2iO/T0hxK6gtACTT/L+7UY7wG12xQqkMPd/k9fiwjnd3RWBAwweI1BId/xEPIUS1Vj/obTimCg3wnVpyH4nJyZ78U4guNfp+A9d67y04F8kPwq6rrSLYhtpaKkEj2TZsv8ACSMPM='
    file:
      - "seng-*.zip"
      - "seng-*.tar.gz"
    file_glob: true
    on:
      tags: true
      node: 'stable'
    skip_cleanup: true

addons:
  code_climate:
    repo_token:
      secure: 'hw0yk7WHvanKSnMgI/qPqfmTwvx+Rjmxsq6SzwskqUqyJmZNIDBriVx1ECCXxyw5De+29hxBk9rhLi8fW6YPYQS7UOPYKmepLcmZKoJrheito8wIUCl9dUT3UVFeHeejlXVDwruCERfEBo49gmRxj04pjH6F0lyor9OLXMQJCxrLPnz9s7j8rSoF5QjdqsGUm+l8tBdnSTG60CHLHACtW1FZ7rKrUNoIgeGhwWvHVlWL6vXSsqE/mD8P/E1vGnhuRP3FX4zNntJ+20vVCvOdleY4q1uDQIYh3bwaIRAz+qubyZL71lJSTvZt2r6nVdA7goc+/OZ/aiSTIeAI+co1kSva38bxN8ynoVDKy64xR/fJ9PeWGIp0Om2N/+bfGek4ea/PiosbxSQSSdFetS6EilwU1NuckC7pNCimoSDR42+YQzSn6/7mPnd3QdwYy8eYYB+yk3TK1Dt/86K6oP9/EqYQYVxqwxwiIjITVUb2AnKNfr90c4h6u66ZvADkapcEQ1JmjvRxc9zOMXJhEjc7EJJH7Lg+iontTiEa89Rgl7mZJQ8wsoYviGpetk3DTjfp2FQ8uWLWAOzbu17pnQxtE+6i8esTCAB+JYcLiUYWomNCD9Xs0ihpElaJ3x+25Ehct/zUUSRM2iq+tSmX695UrjqQ5De3X5g4uEGxtlg490o='
